import { Arrow, Button, ContactCta, Eyebrow, Photo, SectionHeading, ServiceIcon } from "@/lib/components/ui";
import Framework from "@/lib/components/framework";
import { pageMetadata, site, solutions } from "@/lib/site";
export const metadata = pageMetadata("How we help", "Customized leadership development, team performance, and organizational development. Keynotes, workshops, consulting, and coaching built around your people.", "/how-we-help");
export default function SolutionsPage() {
  return <><section className="page-hero container"><Eyebrow>Practical solutions. Human progress.</Eyebrow><h1>Your people have potential.<br /><em>Let’s put it into practice.</em></h1><p className="page-intro">The challenge isn’t knowing what to do. It’s doing it consistently, especially when the pressure is real. That’s where we come in.</p><Button href={site.booking} external>Talk about your team</Button></section>
  <div className="container"><nav className="service-jump-links" aria-label="On this page"><a href="#leadership">Leadership development<Arrow/></a><a href="#teams">Team performance<Arrow/></a><a href="#organizations">Organizational development<Arrow/></a></nav><div>{solutions.map((solution,index) => <section id={solution.id} className="service-detail" key={solution.id} data-reveal><span className="service-detail-number">{index+1}</span><div><ServiceIcon kind={solution.icon}/><h2>{solution.title}</h2><p className="service-short">{solution.short}</p></div><div className="service-detail-copy"><p>{solution.detail}</p><ul className="check-list">{solution.outcomes.map(item=><li key={item}>{item}</li>)}</ul><Button href={site.booking} external variant="text">Let’s talk about what you need</Button></div></section>)}</div></div>
  <Framework/>
  <section className="section container split-section"><Photo src="/images/team-workshop.webp" alt="Workshop participants talking and practicing together in small groups"/><div className="split-copy" data-reveal><Eyebrow>Built for your real world</Eyebrow><h2>No two teams are alike.<br /><em>Neither are our programs.</em></h2><p>Every engagement starts by understanding your organization. Interviews, observations, shadowing, listening sessions, and surveys help us see the behaviors and systems shaping performance.</p><p>Then we design the right combination of keynotes, workshops, training, consulting, and coaching. For large-scale work, trusted delivery partners help us scale while keeping the experience personal.</p><Button href="/get-started" variant="outline">See how we work together</Button></div></section>
  <section className="cream-section"><div className="container section"><SectionHeading eyebrow="Across industries. Across roles." title={<>Where people make<br /><em>the difference.</em></>}><p>Our work spans aviation, corporate leadership, education, government, healthcare, and utilities.</p></SectionHeading><div className="results-list"><div className="result-item"><h3>From leadership<br />to the frontline</h3><p>Executive coaching and frontline service training help connect organizational vision with everyday execution.</p></div><div className="result-item"><h3>Across shifts<br />and stakeholders</h3><p>Experience coordinating airlines, contractors, retail partners, and government agencies in complex environments.</p></div><div className="result-item"><h3>From assessment<br />to application</h3><p>Full-cycle solutions informed by your needs, designed for practical use, and connected to performance outcomes.</p></div></div><Button href={site.capability} variant="text" external>Download our capability statement</Button></div></section><ContactCta/></>;
}
